# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: object_detection.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'object_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16object_detection.proto\":\n\x10\x44\x65tectionRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\"\xca\x02\n\x11\x44\x65tectionResponse\x12 \n\x07objects\x18\x01 \x03(\x0b\x32\x0f.DetectedObject\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12\x19\n\x11\x65nergy_efficiency\x18\x03 \x01(\t\x12\x11\n\tcpu_usage\x18\x04 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x05 \x01(\x02\x12\x12\n\nthroughput\x18\x06 \x01(\x02\x12\x17\n\x0f\x65nergy_required\x18\x07 \x01(\x02\x12\x13\n\x0bpower_watts\x18\x08 \x01(\x02\x12\x37\n\x0bserver_data\x18\t \x03(\x0b\x32\".DetectionResponse.ServerDataEntry\x12\x0f\n\x07latency\x18\n \x01(\x02\x1a\x31\n\x0fServerDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"h\n\x0e\x44\x65tectedObject\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x32R\n\x16ObjectDetectionService\x12\x38\n\rDetectObjects\x12\x11.DetectionRequest\x1a\x12.DetectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONRESPONSE_SERVERDATAENTRY']._loaded_options = None
  _globals['_DETECTIONRESPONSE_SERVERDATAENTRY']._serialized_options = b'8\001'
  _globals['_DETECTIONREQUEST']._serialized_start=26
  _globals['_DETECTIONREQUEST']._serialized_end=84
  _globals['_DETECTIONRESPONSE']._serialized_start=87
  _globals['_DETECTIONRESPONSE']._serialized_end=417
  _globals['_DETECTIONRESPONSE_SERVERDATAENTRY']._serialized_start=368
  _globals['_DETECTIONRESPONSE_SERVERDATAENTRY']._serialized_end=417
  _globals['_DETECTEDOBJECT']._serialized_start=419
  _globals['_DETECTEDOBJECT']._serialized_end=523
  _globals['_OBJECTDETECTIONSERVICE']._serialized_start=525
  _globals['_OBJECTDETECTIONSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
